#
# SPDX-License-Identifier: Apache-2.0
#

repository:
  name: fabric-docs-cn
  description: This lab has graduated to the overall Fabric project. 
  homepage: https://github.com/hyperledger/fabric-docs-i18n/tree/master/docs/source/locale/zh_CN
  default_branch: master
  has_downloads: false
  has_issues: true
  has_projects: false
  has_wiki: false
  archived: true
  private: false
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
